### ISSUE TITLE
Moxygen generates nothing

### ISSUE THREAD

**Issue by rnicolas** [sourcey/moxygen#4]
I ran moxygen as is told in the instructions, but the .md file generated is empty.

**Comment by auscaster** [comment]
Hi there, please provide some specifics so I can reproduce the issue

**Comment by rnicolas** [comment]
Hi,

My doxyfile:
[Doxyfile.txt](https://github.com/sourcey/moxygen/files/730059/Doxyfile.txt)
I've added .txt extension because github doesn't recognize the Doxyfile without extension.

The generated XML from Doxygen
[xml.zip](https://github.com/sourcey/moxygen/files/730098/xml.zip)

Then, when I run `moxygen --anchors --output index.md xml` is when I get the empty document.

**Comment by bearsh** [comment]
I seem to have the same problem, empty output file

**Comment by yannrenard** [comment]
I also have same problem ; additional info: running on OSX 10.12.4, installed `npm` and `doxygen` through `brew`, versions are 4.2.0 and 1.8.13 respectively, moxygen version is 0.6.3

**Comment by bearsh** [comment]
seems to be fixed (according to my first testing), thanks

**Comment by auscaster** [comment]
Yes the issue has been fixed :) Let me know if you still have any issues

**Comment by yannrenard** [comment]
this is wonderful !
do you have an idea when it'll be updated on `npm` or shall I try from source ?

**Comment by bearsh** [comment]
it's already updated...

Am 19.05.2017 10:30 nachm. schrieb "Yann Renard" <notifications@github.com>:

this is wonderful !
do you have an idea when it'll be updated on npm or shall I try from source
?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/sourcey/moxygen/issues/4#issuecomment-302804050>, or mute
the thread
